import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const router = useRouter();

let colorClass = "";
if (router.pathname === "/tinder") {
  colorClass = "bgViolet";
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${bodyClass} ${inter.className}`}>{children}</body>
    </html>
  );
}
