import { Inter } from "next/font/google";
import "./globals.css";
import styles from "@/app/page.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let colorClass = "";
/*
if (usePathname() === "/tinder") {
  colorClass = "bgViolet";
}
*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${colorClass} ${inter.className}`}>
        <main className={styles.main}>
          <div className={styles.main__inner}>{children}</div>
        </main>
      </body>
    </html>
  );
}
